=head1 NAME

RfK - Radio freies Krautchan

=head1 DESCRIPTION

RfK is a Webradio based on liquidsoap, icecast2, MySQL and PHP. The idea was to create a platform which is easy to use and available for everyone. To achieve this every user can get his own account for the streamingserver, in our case icecast2, without unnecessary steps. Another important thing is the site itself, it's needed to plan and organize shows. Further more there's an API which we use for our IRC integration. The database is frequently used to save every kind of information (see table structure for more information). The site itself is based on PHP, other parts are written in Perl and Bash. 

=head2 Installation

=over

=item *

Configure C<icecast2> (see C<etc/icecast.xml>).

=item *

Import C<src/scheme-*.sql> and edit C<etc/config.inc.php>.

=item *

Add the mountpoints from the C<icecast2> config to the database.

=item *

Execute C<etc/genLiquidsoap.php> and run C<liquidsoap> with the generated config.

=item *

(Some paths are hardcoded and will look for the radio in C</usr/share/rfk/>)

=back

=head2 Requirements

=over

=item *

Site: Webserver + PHP5 + MySQL

=item *

Backend: icecast2 + liquidsoap

=item *

Eye Candy: rrdtool (+ RRDTool::OO)

=back

=head1 CONTACT

#RfK @ irc.euirc.net

=head1 AUTHOR

teddydestodes, MrLoom and others

=cut

